eureka:
  instance:
    preferIpAddress: false
    hostname: ${COMPUTERNAME}
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8069/eureka/
