spring:
  application:
    name: Config-Default
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8069/eureka/
  instance:
    preferIpAddress: true
    hostname: localhost
