eureka:
  client:
    service-url:
      defaultZone: http://localhost:8069/eureka/
  instance:
    preferIpAddress: false
    hostname: ${COMPUTERNAME}
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
